### ISSUE TITLE
Upload data

### ISSUE THREAD

**Issue by ronaldtse** [interscript/khmer-dict-spice#1]
@monyoudom could you upload the extracted data in CSV format? Thanks.

**Comment by monyoudom** [comment]
I have upload all khmer words I have collected so far in this google drive [Khmer words dataset](https://drive.google.com/drive/folders/1Xsl1XCSScpwRCU5u23iBocir-0OlApp7?usp=sharing)

**Comment by ronaldtse** [comment]
@monyoudom can you directly upload the dataset contents to https://github.com/interscript/khmer-dict-spice ? Thanks.

**Comment by ronaldtse** [comment]
Thanks!
